name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 2 * * *"
  # allows manually running the job from the Actions tab
  workflow_dispatch:
  # regenerate whenever the profile repo is updated
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # generates a snake game from ankur1072003's contribution graph
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%230891B2&color_dots=%23E8EEFA,%23DCE6F7,%237C3AED,%230891B2,%23DB2777
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2322D3EE&color_dots=%23111C38,%231B2B4A,%23A855F7,%2322D3EE,%23FF3D81

      # push the content of dist/ to the "output" branch
      # files become available at
      # https://raw.githubusercontent.com/ankur1072003/ankur1072003/output/<file>
      - name: push snake svgs to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
